- hosts: appserver
  remote_user: ubuntu
  become_method: sudo
  become_user: root
  become: yes

  vars:
    jdk_package: openjdk-8-jdk
    app_version: 0.0.2-SNAPSHOT
    script_appstart: deploy_java.sh
    work_dir: /usr/local
  tasks:
    - name: Make sure that JDK is installed
      apt:
        name: "{{ jdk_package }}"
        update_cache: true
        state: latest
    - name: Make sure that JAR file is copied
      copy:
        src: "/home/ubuntu/microserviceapp/demo-backend1/target/sentiment-analysis-web-{{ app_version }}.jar"
        dest: "{{ work_dir }}/sentiment-analysis-web-{{ app_version }}.jar"
    - name: Make sure that java app restart script is copied to the remote app server
      copy:
        src: "{{ script_appstart }}"
        dest: "{{ work_dir }}/{{ script_appstart }}"
        mode: '755'
    - name: make sure that JAVA App is running
      shell:
        chdir: "{{ work_dir }}"
        cmd: "./{{ script_appstart }}"
